<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
<title><?php echo $GLOBALS['db']->config->siteName;?></title>
<link href="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('template/recoup/css/bootstrap.css');?>" rel="stylesheet" type="text/css" media="all">
<link href="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('template/recoup/css/style.css');?>" rel="stylesheet" type="text/css" media="all" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content=<?php echo $GLOBALS['db']->config->siteName;?>" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('template/recoup/css/swipebox.css');?>">
<?php if($GLOBALS['db']->config->useCDN === true) : ?>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<?php else: ?>
<script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/jquery/jquery.min.js"></script>
<?php endif; ?>
<script type="text/javascript" src="<?php echo $GLOBALS['db']->config->staticUrl;?>template/recoup//js/move-top.js"></script>
       <script type="text/javascript" src="<?php echo $GLOBALS['db']->config->staticUrl;?>template/recoup/js/easing.js"></script>
		<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){		
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},1200);
				});
			});
		</script>
		<script type="text/javascript">
		$(document).ready(function() {
				/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear' 
				};
				*/
		$().UItoTop({ easingType: 'easeOutQuart' });
});
</script>
<!------ Light Box ------>
    <script src="<?php echo $GLOBALS['db']->config->staticUrl;?>template/recoup/js/jquery.swipebox.min.js"></script> 
    <script type="text/javascript">
		jQuery(function($) {
			$(".swipebox").swipebox();
		});
	</script>
    <!------ Eng Light Box ------>
<?php $GLOBALS['template']->renderBlock('head'); ?>
</head>
<body>
<!-- header -->
	<div class="banner">
		<div class="container">
			<div class="logo">
				<h1><a href="<?php echo $GLOBALS['db']->config->url;?>"><?php echo $GLOBALS['db']->config->siteName;?></a></h1>
			</div>	
			<div class="banner-info">
				<?php $GLOBALS['template']->renderBlock('header'); ?>
			</div>
		</div>
	</div>
<!-- header -->
<!-- contact -->
        <div class="scroll">
                    <a href="#contact" class="scroll"><img src="images/down.png" class="img-responsive" alt=""></a>
	</div>
	<div class="contact" id="contact">
		<div class="container">
                    <?php $GLOBALS['template']->renderBlock('middle'); ?>
		</div>
		<?php $GLOBALS['template']->renderBlock('footer'); ?>
	</div>
	<a href="#" id="toTop" style="display: block;"><span id="toTopHover" style="opacity: 0;"></span> <span id="toTopHover" style="opacity: 0;"> </span></a>
<!-- contact -->
</body>
</html>