<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
<title><?php echo $GLOBALS['db']->config->siteName;?></title>
<link href="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('template/recoup/css/bootstrap.css');?>" rel="stylesheet" type="text/css" media="all">
<link href="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('template/recoup/css/custom.css');?>" rel="stylesheet" type="text/css" media="all" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="<?php echo $GLOBALS['db']->config->siteName;?>" />
<?php $GLOBALS['template']->renderBlock('head'); ?>
</head>
<body>
<!-- header -->
	<div class="header">
		<div class="container">
			<div class="logo">
				<h1><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>"><?php echo $GLOBALS['db']->config->siteName;?></a></h1>
			</div>	
			<div class="navigation">
                                <?php $GLOBALS['template']->renderBlock('header'); ?>
                        </div>
                    </div>
        </div>
<!-- client -->
<!-- contact -->
	<div class="contact" id="contact">
		<div class="container">
                    <?php $GLOBALS['template']->renderBlock('middle'); ?>
		</div>
	</div>
	<a href="#" id="toTop" style="display: block;"><span id="toTopHover" style="opacity: 0;"></span> <span id="toTopHover" style="opacity: 0;"> </span></a>
        <script>
        currentPage = "<?php echo $GLOBALS['db']->config->baseUrl.$GLOBALS['template']->getControl()->getPage(); ?>";
        </script>
        <?php if($GLOBALS['db']->config->useCDN === true) : ?>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('js/common/common.js.gz');?>"></script>
        <?php else: ?>
        <script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/jquery/jquery.min.js"></script>
        <script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/common/common.js"></script>
        <?php endif; ?>
        <?php $GLOBALS['template']->renderBlock('footer'); ?>
<!-- contact -->
</body>
</html>