<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
<title><?php echo $GLOBALS['db']->config->siteName;?></title>
<?php if($GLOBALS['db']->config->useCDN === true) : ?>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<?php else: ?>
<link href="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('style/bootstrap/dist/css/bootstrap.css');?>" rel="stylesheet" type="text/css" media="all">
<?php endif; ?>
<link href="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('template/recoup/css/custom.css');?>" rel="stylesheet" type="text/css" media="all" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="<?php echo $GLOBALS['db']->config->siteName;?>" />
<?php $GLOBALS['template']->renderBlock('head'); ?>
</head>
<body>
        <?php if (
                $GLOBALS['db']->config->googleAnalitycs != '' &&
                (
			!array_key_exists('profile', $GLOBALS) ||
			!is_object($GLOBALS['profile']) ||
	                $GLOBALS['profile']->getData('role_id') != 1
		)
        ) : ?>
    	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', '<?php echo $GLOBALS['db']->config->googleAnalitycs; ?>', 'auto');
	  ga('send', 'pageview');

	</script>
        <?php endif; ?>
<!-- header -->
	<div class="header">
		<div class="container">
			<div class="logo">
				<h1><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>"><?php echo $GLOBALS['db']->config->siteName;?></a></h1>
			</div>	
			<div class="navigation">
                                <?php $GLOBALS['template']->renderBlock('header'); ?>
                        </div>
                    </div>
        </div>
<!-- client -->
<!-- contact -->
	<div class="contact" id="contact">
		<div class="container">
                    <?php $GLOBALS['template']->renderBlock('middle'); ?>
		</div>
	</div>
	<a href="#" id="toTop" style="display: block;"><span id="toTopHover" style="opacity: 0;"></span> <span id="toTopHover" style="opacity: 0;"> </span></a>
        <script>
        currentPage = "<?php echo $GLOBALS['db']->config->baseUrl.$GLOBALS['template']->getControl()->getPage(); ?>";
        </script>
        <?php if($GLOBALS['db']->config->useCDN === true) : ?>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="<?php echo $GLOBALS['db']->config->staticUrl.$GLOBALS['template']->getUrlModifyTimestamp('js/common/common.js.gz');?>"></script>
        <?php else: ?>
        <script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/jquery/jquery.min.js"></script>
        <script src="<?php echo $GLOBALS['db']->config->staticUrl;?>js/common/common.js"></script>
        <?php endif; ?>
        <?php $GLOBALS['template']->renderBlock('footer'); ?>
<!-- contact -->
</body>
</html>