<?php if ($profileColl->count() == 0) : ?>
<div>Nesun utente reperito</div>
<?php else: ?>
<div class="container-fluid">
    <div class="row">
        <div class="col-xs-4">Aggiungi</div>
        <div class="col-xs-4">Nome</div>
        <div class="col-xs-4">Email</div>
    </div>
<?php endif;
foreach($profileColl->getItems() as $profile) : ?>
<div class="row">
    <div class="col-xs-4">
    <?php echo $profile->getData('id'); ?>
    </div>
    <div class="col-xs-4">
    <?php echo $profile->getData('first_name'); ?>
    <?php echo $profile->getData('last_name'); ?>
    </div>
    <div class="col-xs-4">
    <?php echo $profile->getData('email'); ?>
    </div>
</div>
<?php endforeach; ?>
</div>