<?php if($GLOBALS['db']->config->useCDN === true) : ?>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<?php else : ?>
<link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->baseUrl;?>js/jqueryui/themes/base/jquery-ui.min.css">
<?php endif;
$beloved = new \mementomei\Beloved($GLOBALS['db']);
if (array_key_exists('id', $_REQUEST)) {
   $beloved->loadFromId($_REQUEST['id']);
} else {
   $beloved->setData($_REQUEST);
}
?>
<div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php">Home</a></p> &gt; <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=deceased">Elenco defunti</a></p> &gt; <h2>Modifica defunto</h2>
</div>
<form method="post" action="#">
   <input type="hidden" id="id" name="id" value="<?php echo $beloved->getData('id')?>">
   <div>
   <label for="first_name">Nome</label>
   <input id="first_name" name="first_name" value="<?php echo $beloved->getData('first_name')?>" data-oldvalue="<?php echo $beloved->getData('first_name')?>">
   </div>
   <div>
   <label for="last_name">Cognome</label>
   <input id="last_name" name="last_name" value="<?php echo $beloved->getData('last_name')?>" data-oldvalue="<?php echo $beloved->getData('last_name')?>">
   </div>
   <div>
   <label for="description">Denominazione</label>
   <input id="description" name="description" value="<?php echo $beloved->getData('description')?>">
   </div>
   <div>
   <div>
   <label for="date_of_birth">Data di nascita</label>
   <input id="date_of_birth" name="date_of_birth" type="date" value="<?php echo $beloved->getData('date_of_birth')?>">
   </div>
   <div>
   <label for="date_of_death">Data di decesso</label>
   <input id="date_of_death" name="date_of_death" type="date" value="<?php echo $beloved->getData('date_of_death')?>">
   </div>
   <div>
   <label for="epitaph">Epitaffio</label>
   <textarea id="epitaph" name="epitaph"><?php echo $beloved->getData('epitaph')?></textarea>
   </div>
   <p>Creato il:<?php echo $beloved->getData('creation_datetime')?></p>
   <p>Aggiornato il:<?php echo $beloved->getData('change_datetime')?></p>
   <div>
    <div>
    <p><h5>Associa utente</h5></p>
        <div>
            <label for="beloving_search">Cerca in nome, cognome e denominazione</label>
            <input type="search" id="beloving_search" data-url="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=beloved&amp;action=beloving_search"/>
            <img style="display: none;" src="<?php echo $GLOBALS['db']->config->baseUrl;?>/style/general/images/ajax-loader.gif">
            <div id="beloving_search_list"></div>
        </div>
    </div>
    <div>
    <p><h5>Utenti associati</h5></p>
    <div id="beloving_list">
    <?php $belovingColl = $beloved->getBelovingColl();
     if ($belovingColl->count() == 0) : ?>
        <div>Nessun utente reperito</div>
    <?php else: ?>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-6">Nome</div>
            <div class="col-xs-6">Email</div>
        </div>
    <?php foreach($belovingColl->getItems() as $beloving) : ?>
    <div class="row">
        <div class="col-xs-6">
            <a class="actions delete removedBeloved" href="#"><input type="hidden" name="beloving[]" value="<?php echo $beloving->getData('id'); ?>"></a>
        <?php echo $beloving->getData('first_name'); ?>
        <?php echo $beloving->getData('last_name'); ?>
        </div>
        <div class="col-xs-6">
        <?php echo $beloving->getData('email'); ?>
        </div>
    </div>
    <?php endforeach; ?>
    </div>
    <?php endif;?>        
    </div>
    </div>
    <div>
    <p><h5>Associa cimitero</h5></p>
        <div>
            <label for="graveyard_search">Cerca in nome e città</label>
            <input type="search" id="graveyard_search" data-url="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=beloved&amp;action=graveyard_search"/>
            <img style="display: none;" src="<?php echo $GLOBALS['db']->config->baseUrl;?>/style/general/images/ajax-loader.gif">
            <div id="graveyard_search_list"></div>
        </div>
    </div>
    <div>
    <p><h5>Cimiteri</h5></p>
    <div id="graveyard_list">
    <?php $graveyardColl = $beloved->getGraveyardColl();
     if ($graveyardColl->count() == 0) : ?>
        <div>Nessun cimitero</div>
    <?php else: ?>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-6">Nome</div>
            <div class="col-xs-6">Email</div>
        </div>
    <?php foreach($graveyardColl->getItems() as $graveyard) : ?>
    <div class="row">
        <div class="col-xs-6">  
            <a class="actions delete removedGraveyard" href="#"><input type="hidden" name="graveyard[]" value="<?php echo $graveyard->getData('id'); ?>"/></a>
        <?php echo $graveyard->getData('name'); ?>
        <?php echo $graveyard->getData('city'); ?>
        </div>
        <div class="col-xs-6">
        <?php echo $graveyard->getData('email'); ?>
        </div>
    </div>
    <?php endforeach; ?>
    </div>
    <?php endif;?>        
    </div>
    </div>
    <div>
    <p><h5>Associa agenzia</h5></p>
        <div>
            <label for="parlour_search">Cerca in nome e città</label>
            <input type="search" id="parlour_search" data-url="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=beloved&amp;action=parlour_search"/>
            <img style="display: none;" src="<?php echo $GLOBALS['db']->config->baseUrl;?>/style/general/images/ajax-loader.gif">
            <div id="parlour_search_list"></div>
        </div>
    </div>
    <div>
    <p><h5>Agenzie</h5></p>
    <div id="parlour_list">
    <?php $parlourColl = $beloved->getParlourColl();
     if ($parlourColl->count() == 0) : ?>
        <div>Nessun agenzia</div>
    <?php else: ?>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-6">Nome</div>
            <div class="col-xs-6">Email</div>
        </div>
    <?php foreach($parlourColl->getItems() as $parlour) : ?>
    <div class="row">
        <div class="col-xs-6">  
            <a class="actions delete removedParlour" href="#"><input type="hidden" name="parlour[]" value="<?php echo $parlour->getData('id'); ?>"/></a>
        <?php echo $parlour->getData('name'); ?>
        <?php echo $parlour->getData('city'); ?>
        </div>
        <div class="col-xs-6">
        <?php echo $parlour->getData('email'); ?>
        </div>
    </div>
    <?php endforeach; ?>
    </div>
    <?php endif;?>        
    </div>
    </div>
    </div>
   <div>
      <input type="submit" name="submit" value="Salva">
   </div>
</form>

