<?php if($GLOBALS['db']->config->useCDN === true) : ?>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/base/jquery-ui.min.css"></script>
<link rel="stylesheet" href="//cdn.datatables.net/1.10.3/css/jquery.dataTables.min.css">
<?php else : ?>
<link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->baseUrl;?>/js/jqueryui/themes/base/jquery-ui.min.css">
<link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->baseUrl;?>/js/DataTables/media/css/jquery.dataTables.css">
<?php endif; ?>
<div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php">Home</a></p> &gt; <h2>Deceduti</h2>
</div>
<a id="addCategoryTaxa" class="actions add" title="Aggiungi" href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=beloved&amp;action=edit">Aggiungi</a>
<table id="belovedT">
   	<thead>
		<tr>
			<th data-bSortable="false" data-sName="id" data-bVisible="false">Id</th>
			<th data-sName="first_name" >Nome</th>
                        <th data-sName="last_name" >Cognome</th>
                        <th data-sName="description" >Denominazione</th>
                        <th data-sName="date_of_birth" >Data di nascita</th>
                        <th data-sName="date_of_death" >Data di decesso</th>
                        <th data-bSortable="false" data-sName="actions" >Azioni</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td colspan="7" class="dataTables_empty">Carico i dati</td>
		</tr>
	</tbody>
	<tfoot>
		<tr>
                        <th>Id</th>
			<th>Nome</th>
                        <th>Cognome</th>
                        <th>Denominazione</th>
                        <th>Data di nascita</th>
                        <th>Data di decesso</th>
                        <th>Azioni</th>
		</tr>
	</tfoot>
</table>