<?php $role = $GLOBALS['profile']->getRole();?>
<ul>
   <?php if ($role->getData('id') >0 && $role->getData('id') <= 1) : ?>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=beloved">Defunti</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=graveyard">Cimiteri</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=parlour">Agenzie</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=memento">Presenti</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=user">Utenti</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=content">Contenuti dinamici</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=contact">Contatti</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=log">Log</a></li>
   <li><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php?task=backup">Backup/Restore</a></li>
   <?php endif; ?>
</ul>