<?php if($GLOBALS['db']->config->useCDN === true) : ?>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/base/jquery-ui.min.css"></script>
<link rel="stylesheet" href="//cdn.datatables.net/1.10.3/css/jquery.dataTables.min.css">
<?php else : ?>
<link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->baseUrl;?>/js/jqueryui/themes/base/jquery-ui.min.css">
<link rel="stylesheet" href="<?php echo $GLOBALS['db']->config->baseUrl;?>/js/DataTables/media/css/jquery.dataTables.css">
<?php endif; ?>
<div id="breadcrump">
   <p><a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php">Home</a></p> &gt; <h2>Presenti</h2>
</div>
<table id="mementoT">
   	<thead>
		<tr>
			<th data-bSortable="false" data-sName="code" data-bVisible="false">Codice</th>
			<th data-sName="name" >Nome</th>
                        <th data-bSortable="false" data-sName="actions" >Azioni</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td colspan="7" class="dataTables_empty">Carico i dati</td>
		</tr>
	</tbody>
	<tfoot>
		<tr>
                        <th>Codice</th>
			<th>Nome</th>
                        <th>Azioni</th>
		</tr>
	</tfoot>
</table>