<ul >
<li>
    <a href="<?php echo $GLOBALS['db']->config->baseUrl;?>contact.php">Contattaci</a>
</li>
<?php  if ($GLOBALS['profile'] instanceof \login\user\Profile) : ?>
<li>
    <a href="<?php echo $GLOBALS['db']->config->baseUrl;?>administrator.php">Amministrazione</a>
</li>
<li>
    <a href="<?php echo $GLOBALS['db']->config->baseUrl;?>?logout">Esci</a></li>
</li>
<?php else: ?>
<li >
    <a href="<?php echo $GLOBALS['db']->config->baseUrl;?>user.php">Accedi/registrati</a>
</li>
<?php endif; ?>
</ul>