<?php
if(
        array_key_exists('profile',$GLOBALS) &&
        $GLOBALS['profile'] instanceof \login\user\Profile &&
        $GLOBALS['profile']->getData('role_id') == 4
   ) : ?>
<p>HI</p>
<?php else :
$content = new \content\content\Content($GLOBALS['db']);
$content->loadFromLabel('home');?>
   <div>
   <h1>
      <?php echo $content->getData('title');?>
   </h1>
   <h2>
      <?php echo $content->getData('abstract');?>
   </h2>    
   <div>
      <?php echo $content->getData('content');?>
   </div>
<?php endif;
